namespace SweetManagerWebService.IAM.Interfaces.REST.Resource.Authentication.User;

public record SignUpUserResource(string Username, 
    string Name, string Surname, string Email, int Phone, string State, string Password)
{
    // ID will be auto-generated by the database
};
